### PR TITLE
Fixes appeal tab issues

### LINKED ISSUE #1414: Web: Appeal tab not being immediately available/clickable
Appeal tab not being immediately available/clickable when the frontend refetches from subgraph and we are on Appeal period. It is not until you refresh the website that you can see it available/clickable.

https://github.com/kleros/kleros-v2/assets/102478601/55704bd3-f658-4090-b91d-4c0f3382e78a

### LINKED ISSUE #1416: Web: Appeal on StageTwo is not showing StageOne information
Possible solution: (1) In StageTwo, show the option that was appealed in StageOne. it can be even just as text, informational.

A community user complains that he did not know there was an appeal on the stage one of the appeal period. The problem here is, when you are on the second stage of appealing, there is no information about WHICH OPTION WAS appealed on stage one, or even IF there was an option appealed at all on stage one. Video to illustrate:

https://github.com/kleros/kleros-v2/assets/102478601/9918efd4-2f68-4565-9393-595225d7e304

More information for context on the user complaint translated:

```
At the time of voting, a sign appeared asking to vote "refuse to arbitrate."
One of the parties appeals, but it is not seen on the screen that this has happened.
This is good?

When the first appeal period expires, only the second appeal option appears on the screen, without showing whether the other party appealed or not.

Furthermore, the jury decision win appeared on the deadline, so I did not appeal, thinking that the first part of the appeal had not been done.

The outcome of that stage one was not clear when you are on stage two

I never knew it had been appealed at the beginning so I didn't appeal again.
```

### PR DESCRIPTION
**Pull request by Harman-singh-waraich**
closes #1414 , closes #1416 

Issues fixed by this PR :

1. Appeal tab becomes active after period changes to Appeal, no need to reload
2. Explainer for stage 2, to show info about stage 1 's funded choice
3. Popup showing on user reject txn, now fixed
4. Fund button updated, better disabling conditions
5. Fixes fully funded option still selectable
6. Fixes fund input not editable in stage 2 appeal
7. Adds loading indicator while appeal data is loading, instead of showing "No option was funded" info

---

## PR-Codex overview
This PR focuses on refactoring the appeal feature in the CaseDetails page. It includes the following changes:

- Renamed the `useLoserSideCountdownContext` hook to `useCountdownContext` and added `useWinnerSideCountdown` hook.
- Updated imports and dependencies in multiple files.
- Added `StageOneExplanation` and `StageTwoExplanation` components.
- Updated the `StageExplainer` component to handle different stages.
- Updated the `Tabs` component to disable a tab based on certain conditions.
- Updated the `Options` component to use the `useCountdownContext` hook.
- Updated the `StageOne` component to use the `useCountdownContext` and `useFundingContext` hooks.
- Updated the `StageTwo` component to use the `useCountdownContext`, `useFundingContext`, and `useOptionsContext` hooks.
- Updated the `ClassicAppealProvider` component to use the `useCountdownContext` hook and provide the countdown values.
- Updated the `useClassicAppealContext` hook to export the `useCountdownContext` hook.
- Added the `useWinnerSideCountdown` hook.
- Updated the `getDeadline` function in the `useClassicAppealContext` hook.
- Updated the `Fund` component to use the `useAccount`, `useBalance`, and `usePublicClient` hooks.

> The following files were skipped due to too many changes: `web/src/pages/Cases/CaseDetails/Appeal/Classic/Fund.tsx`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by kemuru — APPROVED** [review]
lgtm

File: web/src/pages/Cases/CaseDetails/Appeal/Classic/StageExplainer.tsx [hunk 1]
```diff
@@ -31,24 +35,63 @@ const CountdownLabel = styled.label`
...
+  const options = useOptionsContext();
+  return (
     <div>
       <label>
-        Losing options can only be funded <small>before</small> the deadline.
+        Loser deadline has <small>finalized</small>, you can only fund the current winner.
+      </label>
+      <label>
+        The sum of funds must reach 100%. If it's not fully funded in time the option fully funded at{" "}
+        <small>stage 1</small> is declared the winner of the case.{" "}
```
Comment (alcercu) [inline web/src/pages/Cases/CaseDetails/Appeal/Classic/StageExplainer.tsx:64]: This is slightly inaccurate, for the current implementation of `DisputeKitClassic` the sum of funds is not considered, the only condition to make an appeal go through is to completely fund two options. So I would write something like this:
```If the current winner is not fully funded in time, the option funded during the previous stage will be declared as the final winner.```

**Review by alcercu — CHANGES_REQUESTED** [review]
