### PR TITLE
fix(web): link-behaviour-in-dispute-card

### LINKED ISSUE #1630: UX bug: accidental redirection to the court when clicking on blank space
clicking on the blank space between "Court" and the court itself inside a Dispute Card will lead you to the court, but clicking on this blank space itself should not lead you to the court, but the case itself. so maybe the Field's Link shouldn't occupy full width

image

RELATED CODE:
https://github.com/kleros/kleros-v2/blob/dev/web/src/components/DisputeView/DisputeInfo/DisputeInfoCard.tsx#L81-L84
https://github.com/kleros/kleros-v2/blob/dev/web/src/components/Field.tsx#L96-L112

### PR DESCRIPTION
**Pull request by Harman-singh-waraich**
closes #1630

---

## PR-Codex overview
The focus of this PR is to refactor the `Link` component in `Field.tsx` to use styled components for better styling and event handling.

### Detailed summary
- Refactored `Link` component to use styled components
- Added `LinkContainer` and `StyledLink` styled components
- Improved styling and event handling for links

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

## Summary by CodeRabbit

- **Refactor**
  - Improved the structure and readability of the `Field` component by refactoring link styling into new `LinkContainer` and `StyledLink` components. This change enhances the modularity and encapsulation of link styling.

### CODE REVIEW

File: web/src/components/Field.tsx [hunk 1]
```diff
@@ -62,6 +56,15 @@ const FieldContainer = styled.div<FieldContainerProps>`
     `};
 `;
 
+const LinkContainer = styled.div`
+  display: flex;
+  justify-content: end;
```
Comment (kemuru) [inline web/src/components/Field.tsx:61]: the correct form is `justify-content: flex-end`, but anyways this is not doing anything i think? we can just delete it & leave it as const ` LinkContainer = styled.div`` ` wdyt

**Review by kemuru — APPROVED** [review]

**Review by alcercu — APPROVED** [review]
lgtm
